### ISSUE TITLE
Loading issues

### ISSUE THREAD

**Issue by William-Ramsay** [rharish101/dilbert-viewer#18]
10s load time minimum and frequent internal errors

**Comment by xanderman** [comment]
I'm seeing the same thing. I was reading a week's worth of comics, and it started slowing after a couple and then failing at https://dilbert-viewer.herokuapp.com/2020-11-11. I refreshed a few times and collected the error messages in case it helps:

`HTTP client error: Error sending request: Timeout while waiting for response`
`Scraping error: Error in scraping the image's details`
`HTTP client error: Error sending request: Failed to connect to host: Connection refused (os error 111)`
`Scraping error: Couldn't scrape comic: b"<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>\n"`

"Scraping error" was the most common.

**Comment by rharish101** [comment]
Thanks for the example @xanderman! I found the bug, and I've pushed a fix for that. As for the loading times (@William-Ramsay), I think the recent DDoS at archive.org might be contributing to it, since most of the time this website spends is in scraping archive.org.

**Comment by rharish101** [comment]
Feel free to reopen the issue (or comment so that I can reopen it) if you still see errors!
