### ISSUE TITLE
quit working

### ISSUE THREAD

**Issue by timpiker** [rharish101/dilbert-viewer#21]
I've been using the Dilbert Viewer for a yr and a half without flaw.  Thank you!  I noticed that it seemed to quit working last week.

**Comment by rharish101** [comment]
Thanks for notifying! I think it's because of all the DDoSes that the Wayback Machine (archive.org) is getting.

**Comment by rharish101** [comment]
Looks like it's back up now!

**Comment by timpiker** [comment]
Yes, thanks.  It came back on shortly after I reported it.


Tim
________________________________
