### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by ecstrema** [rharish101/dilbert-viewer#8]
It's so much nicer to use than the web archive!

Ok two small issues:

1) Since the image is not always the same size, you always need to move your mouse around to click the ">" (next) button. I see 2 solutions: 1) add a shortcut: left and right arrow would be perfect or 2) move the buttons to the left of the image. The second is less ideal though.
2) I'd like to save my favorites. Could that be saved to local storage? 
3) Since we almost always almost want to go to either the next or the previous page, could we prefetch it, so that navigation is faster?

As far as I know, the simplest way to achieve that is still with something like:

```html
<script>
    function prefetchResource(url) {
        var link = document.createElement("link");
        link.rel = "prefetch";
        link.href = url;
        document.head.appendChild(link);
    }
</script>
<!-- ... -->
<a href="/x" onmouseover="prefetchResource('/x')">Link to /x</a>
```

I wish I could help there, but I've never used rust any rust powered web framework, so....

**Comment by rharish101** [comment]
I've implemented points 1 & 3. Try them out, and see if it works.

As for point 2, you can simply use your browser to bookmark the links in a folder. I just feel that adding this would be unnecessary bloat for a website designed as a simple viewer, especially when most webcomics don't have this on their webpage.

**Comment by ecstrema** [comment]
Wow that was quick. 

You're right for point two.

Thanks again.
